# Generated by Django 4.2.28 on 2026-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_alter_menuitem_description_alter_menuitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
    ]
